name: build-pickles
on: [push]
jobs:
    build:
        runs-on: windows-latest
        
        steps:
        - uses: actions/checkout@v1
          name: Checkout Code

        - name: Setup NuGet
          uses: NuGet/setup-nuget@v1.0.5
          #with:
            # NuGet API Key to configure.
            #nuget-api-key: # optional
            # Source to scope the NuGet API Key to.
            #nuget-api-key-source: # optional

        - name: Restore NuGet Packages
          run: nuget restore src\pickles\pickles.sln

        #- name: Build and Publish Web App
        #  run: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild SimpleFrameworkApp.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

        #- name: Upload Artifact
        #  uses: actions/upload-artifact@v1.0.0
        #  with:
        #    name: published_webapp
        #    path: bin\Release\Publish
